// Hong Kong–style teaching values, not a complete ruleset or an odds calculator.
// Decisions assume a three-fan minimum and favor preserving completed sets.
export const lessons = [
  {
    id: 'chicken',
    title: 'Chicken hand',
    fan: '0 fan',
    summary: 'Four sets and a pair can be structurally complete without scoring enough.',
    detail: 'This mixed-suit hand has no scoring pattern in our teaching rules. With a three-fan minimum, a zero-fan chicken hand cannot win. A quick completion is not enough: plan a qualifying pattern. Examples assume east is the round wind and south is your seat wind.',
    example: ['m1', 'm2', 'm3', 'p4', 'p5', 'p6', 's7', 's8', 's9', 'm2', 'm3', 'm4', 'W', 'W'],
  },
  {
    id: 'all-pungs',
    title: 'All pungs',
    fan: '3 fan',
    summary: 'Build four three-of-a-kind sets and one pair.',
    detail: 'Every set must be a pung; a sequence breaks this pattern. All pungs provides the three-fan minimum by itself. Dragon or value-wind pungs can add fan, and a one-suit-plus-honors all-pungs hand can also score half flush.',
    example: ['m2', 'm2', 'm2', 'p5', 'p5', 'p5', 's8', 's8', 's8', 'W', 'W', 'W', 'E', 'E'],
  },
  {
    id: 'half-flush',
    title: 'Half flush',
    fan: '3 fan',
    summary: 'Use exactly one numbered suit together with honors.',
    detail: 'Sequences and pungs are both allowed. Keep at least one honor set or honor pair, and remove the other numbered suits. Half flush meets the minimum by itself; value honor pungs can add fan. It cannot also score full flush.',
    example: ['m1', 'm2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9', 'W', 'W', 'W', 'E', 'E'],
  },
  {
    id: 'full-flush',
    title: 'Full flush',
    fan: '7 fan',
    summary: 'Make every set and the pair from one numbered suit, with no honors.',
    detail: 'A full flush scores seven fan in this trainer. Do not keep a dragon or wind just because it might score: any honor prevents full flush. Half flush and full flush are mutually exclusive, not seven plus three.',
    example: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p2', 'p2', 'p2', 'p5', 'p5'],
  },
  {
    id: 'dragons',
    title: 'Dragon pungs',
    fan: '1 fan each',
    summary: 'A pung of red, green, or white dragons adds one fan.',
    detail: 'R is red, G is green, and B is white. A dragon pair scores nothing here. The example has one dragon pung and only one fan, so it is below the three-fan minimum. Use dragon pungs as additions to a qualifying plan such as all pungs or half flush, not as an automatic three-fan route.',
    example: ['R', 'R', 'R', 'm1', 'm2', 'm3', 'p4', 'p5', 'p6', 's7', 's8', 's9', 'W', 'W'],
  },
  {
    id: 'winds',
    title: 'Value winds',
    fan: '1 fan per matching wind',
    summary: 'A seat-wind pung or round-wind pung adds one fan; a double-value pung adds two.',
    detail: 'With east round and south seat, EEE and SSS each score one fan. This example totals only two fan and cannot win at the three-fan minimum. If both round and seat are east, EEE scores two fan, not one. Wind pairs and non-value wind pungs score no wind fan. Combine value winds with a qualifying foundation.',
    example: ['E', 'E', 'E', 'S', 'S', 'S', 'm1', 'm2', 'm3', 'p4', 'p5', 'p6', 'W', 'W'],
  },
];

export const scenarios = [
  {
    id: 'three-pungs-two-pairs',
    title: 'Three pungs, two useful pairs',
    difficulty: 'Beginner',
    roundWind: 'E',
    seatWind: 'S',
    stage: 'Late drawn turn · three-fan minimum · preserve the three completed pungs',
    hand: ['m2', 'm2', 'm2', 'p5', 'p5', 'p5', 's8', 's8', 's8', 'E', 'E', 'W', 'W', 'm9'],
    exposed: [],
    options: [
      { id: 'all-pungs', label: 'All pungs' },
      { id: 'half-flush', label: 'Half flush' },
      { id: 'full-flush', label: 'Full flush' },
    ],
    bestPattern: 'all-pungs',
    discards: ['m9'],
    explanation: 'Discard the isolated 9 of characters. Keep all three pungs and both wind pairs: another east or west makes the fourth pung, leaving the other wind as the pair. All pungs supplies three fan; an east pung adds one round-wind fan.',
    tradeoff: 'Either flush would dismantle completed pungs in two suits. This lesson favors the ready all-pungs shape, not a speculative higher-value rebuild.',
    targetFan: '3 fan; 4 if east becomes a pung',
  },
  {
    id: 'open-pungs-finish',
    title: 'Finish the open pung plan',
    difficulty: 'Beginner',
    roundWind: 'E',
    seatWind: 'S',
    stage: 'Late drawn turn · three-fan minimum · two exposed pungs are fixed',
    hand: ['s2', 's2', 's2', 'E', 'E', 'R', 'R', 'p1'],
    exposed: [['m4', 'm4', 'm4'], ['p7', 'p7', 'p7']],
    options: [
      { id: 'all-pungs', label: 'All pungs with a value pung' },
      { id: 'half-flush', label: 'Half flush' },
      { id: 'full-flush', label: 'Full flush' },
    ],
    bestPattern: 'all-pungs',
    discards: ['p1'],
    explanation: 'Discard the isolated 1 of circles. Retain the bamboo pung and the east and red pairs. Drawing east or red completes a fourth pung and leaves a pair: three fan for all pungs plus one for the resulting value pung.',
    tradeoff: 'The exposed character and circle pungs cannot be taken back, so neither flush is available. A value pair alone does not score.',
    targetFan: '4 fan',
  },
  {
    id: 'characters-and-winds',
    title: 'Keep the character sequences',
    difficulty: 'Beginner',
    roundWind: 'E',
    seatWind: 'S',
    stage: 'Late drawn turn · three-fan minimum · keep three completed sequences',
    hand: ['m1', 'm2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9', 'E', 'E', 'S', 'S', 'p9'],
    exposed: [],
    options: [
      { id: 'half-flush', label: 'Half flush with a value wind' },
      { id: 'full-flush', label: 'Full flush' },
      { id: 'all-pungs', label: 'All pungs' },
    ],
    bestPattern: 'half-flush',
    discards: ['p9'],
    explanation: 'Discard the only circle, 9 of circles. Keep 123, 456, and 789 of characters with the east and south pairs. Another east or south gives a wind pung and a remaining pair: half flush plus one value-wind fan.',
    tradeoff: 'Full flush requires replacing four useful honor tiles. All pungs would break the three sequences. Preserve this one-tile-away half flush.',
    targetFan: '4 fan',
  },
  {
    id: 'open-bamboo-half-flush',
    title: 'Bamboo with useful honors',
    difficulty: 'Beginner',
    roundWind: 'E',
    seatWind: 'S',
    stage: 'Late drawn turn · three-fan minimum · two bamboo sequences are exposed',
    hand: ['s1', 's2', 's3', 'G', 'G', 'W', 'W', 'm9'],
    exposed: [['s3', 's4', 's5'], ['s6', 's7', 's8']],
    options: [
      { id: 'half-flush', label: 'Half flush' },
      { id: 'all-pungs', label: 'All pungs' },
      { id: 'full-flush', label: 'Full flush' },
    ],
    bestPattern: 'half-flush',
    discards: ['m9'],
    explanation: 'Discard the only character, 9 of characters. Keep 123 of bamboo and both honor pairs. Another green or west completes the last set. Half flush gives three fan even when the non-value west becomes the pung; a green pung adds one.',
    tradeoff: 'Exposed sequences rule out all pungs. Removing both honor pairs to chase full flush abandons a ready half-flush shape.',
    targetFan: '3 fan; 4 if green becomes a pung',
  },
  {
    id: 'circles-no-honors',
    title: 'One circle suit is enough',
    difficulty: 'Beginner',
    roundWind: 'E',
    seatWind: 'S',
    stage: 'Late drawn turn · three-fan minimum · retain the nearly complete single-suit hand',
    hand: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p2', 'p2', 'p5', 'p5', 'E'],
    exposed: [],
    options: [
      { id: 'full-flush', label: 'Full flush' },
      { id: 'half-flush', label: 'Half flush' },
      { id: 'all-pungs', label: 'All pungs' },
    ],
    bestPattern: 'full-flush',
    discards: ['E'],
    explanation: 'Discard the lone east. Keep the three circle sequences and the pairs of 2 and 5. Another 2 or 5 can make the fourth set, leaving the other pair. A completed all-circle hand earns seven fan.',
    tradeoff: 'A single round wind scores nothing. Keeping it for a possible honor set gives up the immediate full-flush plan; half flush is not added to full flush.',
    targetFan: '7 fan',
  },
  {
    id: 'characters-white-distraction',
    title: 'Do not let a dragon dilute the suit',
    difficulty: 'Intermediate',
    roundWind: 'E',
    seatWind: 'S',
    stage: 'Late drawn turn · three-fan minimum · preserve completed character sets',
    hand: ['m2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm8', 'm8', 'm1', 'm1', 'm6', 'm6', 'B'],
    exposed: [],
    options: [
      { id: 'full-flush', label: 'Full flush' },
      { id: 'half-flush', label: 'Half flush' },
      { id: 'dragons', label: 'Build a white dragon pung' },
    ],
    bestPattern: 'full-flush',
    discards: ['B'],
    explanation: 'Discard the lone white dragon. Keep character sequences 234 and 567, the 888 pung, and the 11 and 66 pairs. Another 1 or 6 completes a fourth set and leaves a pair, all in characters.',
    tradeoff: 'White needs two more copies just to form a one-fan pung. That rebuild also prevents the seven-fan full flush; a dragon by itself does not meet the minimum.',
    targetFan: '7 fan',
  },
  {
    id: 'red-dragon-pung-foundation',
    title: 'Red dragons add to all pungs',
    difficulty: 'Beginner',
    roundWind: 'E',
    seatWind: 'S',
    stage: 'Late drawn turn · three-fan minimum · the red dragon pung is exposed',
    hand: ['m2', 'm2', 'm2', 'p6', 'p6', 'p6', 's9', 's9', 'E', 'E', 'p1'],
    exposed: [['R', 'R', 'R']],
    options: [
      { id: 'dragons', label: 'Red dragon pung + all pungs' },
      { id: 'half-flush', label: 'Half flush' },
      { id: 'full-flush', label: 'Full flush' },
    ],
    bestPattern: 'dragons',
    discards: ['p1'],
    explanation: 'Discard the isolated 1 of circles. Keep the character and circle pungs and the bamboo 99 and east pairs. A 9 of bamboo or east completes all pungs for three fan, with one more from the exposed red dragons.',
    tradeoff: 'The red pung alone is only one fan, not a legal minimum-fan win. Half flush would require discarding completed suited pungs, and the exposed dragons prevent full flush.',
    targetFan: '4 fan; 5 if east becomes a pung',
  },
  {
    id: 'green-dragon-bamboo-foundation',
    title: 'Green dragons add to half flush',
    difficulty: 'Intermediate',
    roundWind: 'E',
    seatWind: 'S',
    stage: 'Late drawn turn · three-fan minimum · keep the exposed green pung and bamboo sequences',
    hand: ['s1', 's2', 's3', 's4', 's5', 's6', 's8', 's8', 'R', 'R', 'p9'],
    exposed: [['G', 'G', 'G']],
    options: [
      { id: 'dragons', label: 'Green dragon pung + half flush' },
      { id: 'all-pungs', label: 'All pungs' },
      { id: 'full-flush', label: 'Full flush' },
    ],
    bestPattern: 'dragons',
    discards: ['p9'],
    explanation: 'Discard the only circle, 9 of circles. Retain bamboo 123 and 456, the 88 pair, and the red pair. Another bamboo 8 or red completes the hand: half flush is three fan and the green pung adds one. A red pung adds another.',
    tradeoff: 'The exposed green pung prevents full flush. All pungs would break two completed sequences. Green dragons alone provide only one fan; the bamboo-and-honors foundation qualifies the hand.',
    targetFan: '4 fan; 5 if red becomes a pung',
  },
  {
    id: 'south-seat-circle-foundation',
    title: 'Your seat wind has a foundation',
    difficulty: 'Beginner',
    roundWind: 'E',
    seatWind: 'S',
    stage: 'Late drawn turn · three-fan minimum · the south seat-wind pung is exposed',
    hand: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p8', 'p8', 'E', 'E', 'm9'],
    exposed: [['S', 'S', 'S']],
    options: [
      { id: 'winds', label: 'Seat-wind pung + half flush' },
      { id: 'all-pungs', label: 'All pungs' },
      { id: 'full-flush', label: 'Full flush' },
    ],
    bestPattern: 'winds',
    discards: ['m9'],
    explanation: 'Discard the only character, 9 of characters. Keep circle 123 and 456 plus the circle 88 and east pairs. Another circle 8 or east finishes half flush for three fan, with one extra for your south pung. An east pung adds the round-wind fan.',
    tradeoff: 'The seat-wind pung is one fan, not three. Exposed south prevents full flush, and rebuilding the circle sequences as pungs is unnecessary.',
    targetFan: '4 fan; 5 if east becomes a pung',
  },
  {
    id: 'double-east-pung',
    title: 'East counts twice',
    difficulty: 'Intermediate',
    roundWind: 'E',
    seatWind: 'E',
    stage: 'Late drawn turn · three-fan minimum · east is both seat and round wind',
    hand: ['m3', 'm3', 'm3', 'p7', 'p7', 'p7', 'G', 'G', 's4', 's4', 's9'],
    exposed: [['E', 'E', 'E']],
    options: [
      { id: 'winds', label: 'Double-value east pung + all pungs' },
      { id: 'half-flush', label: 'Half flush' },
      { id: 'full-flush', label: 'Full flush' },
    ],
    bestPattern: 'winds',
    discards: ['s9'],
    explanation: 'Discard the isolated 9 of bamboo. Keep both suited pungs and the green and bamboo 44 pairs. Green or bamboo 4 completes all pungs for three fan. The exposed east pung adds two because it matches both seat and round wind.',
    tradeoff: 'Double east alone is only two fan and still below the minimum. Preserve the all-pungs foundation rather than dismantling the mixed-suit pungs for a flush.',
    targetFan: '5 fan; 6 if green becomes a pung',
  },
  {
    id: 'neutral-honors-still-qualify',
    title: 'Non-value honors can still belong',
    difficulty: 'Intermediate',
    roundWind: 'E',
    seatWind: 'S',
    stage: 'Late drawn turn · three-fan minimum · distinguish structural value from wind fan',
    hand: ['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 'W', 'W', 'N', 'N', 'p5'],
    exposed: [],
    options: [
      { id: 'half-flush', label: 'Half flush with non-value honors' },
      { id: 'chicken', label: 'Ignore patterns and chase a zero-fan hand' },
      { id: 'all-pungs', label: 'All pungs' },
    ],
    bestPattern: 'half-flush',
    discards: ['p5'],
    explanation: 'Discard the only circle, 5 of circles. Keep the three bamboo sequences and both wind pairs. Another west or north makes the fourth set and leaves a pair. Neither wind pung scores a value-wind fan here, but bamboo plus honors qualifies for three-fan half flush.',
    tradeoff: 'A zero-fan chicken hand is not legal at this minimum. Non-value honors need not be thrown away: they fit half flush. All pungs would break all three sequences.',
    targetFan: '3 fan',
  },
  {
    id: 'white-dragon-is-not-enough',
    title: 'One dragon fan is not the whole plan',
    difficulty: 'Intermediate',
    roundWind: 'E',
    seatWind: 'S',
    stage: 'Late drawn turn · three-fan minimum · keep the three completed pungs',
    hand: ['B', 'B', 'B', 'm4', 'm4', 'm4', 'p8', 'p8', 'p8', 'S', 'S', 'N', 'N', 'm1'],
    exposed: [],
    options: [
      { id: 'all-pungs', label: 'All pungs + white dragon pung' },
      { id: 'dragons', label: 'Rely on the white dragon pung alone' },
      { id: 'half-flush', label: 'Half flush' },
    ],
    bestPattern: 'all-pungs',
    discards: ['m1'],
    explanation: 'Discard the isolated 1 of characters. Keep the white, character, and circle pungs with both wind pairs. South or north completes all pungs for three fan, plus one for white dragons. If south becomes the pung, it adds your seat-wind fan.',
    tradeoff: 'The white pung alone supplies only one fan and cannot satisfy the minimum. A half flush would dismantle a completed suited pung; all pungs already fits the hand.',
    targetFan: '4 fan; 5 if south becomes a pung',
  },
];
